version: "3.7"
services:
  memcached:
    image: memcached:1.5-alpine

  convertit:
    image: makinacorpus/convertit:latest

  screamshotter:
    image: makinacorpus/screamshotter:v2

  # delete postgres section if you use external database.
  postgres:
    image: juank/postgis:14-3.1
    volumes:
      - postgres:/var/lib/postgresql/data
    env_file:
      - .env

  web:
    image: ghcr.io/georiviere/georiviere-admin:latest
    depends_on:
      - screamshotter
      - convertit
      - postgres
      - memcached
    env_file:
      - .env
    volumes:
      - ./var:/opt/georiviere-admin/var
#    ports:
#      - "127.0.0.1:8000:8000"  # uncomment to use with external nginx proxy

  # delete nginx section if you want to use external nginx proxy
  nginx:
    image: nginx:latest
    depends_on:
      - web
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ./var/static:/var/www/static
      - ./var/media:/var/www/media

volumes:
  # delete postgres section if you use external database.
  postgres:
