# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Test CI

on:
  pull_request:
  push:
    branches:
      - master
  release:
    types:
      - created
env:
  DEBIAN_FRONTEND: noninteractive

jobs:
  flake8:
    name: Check python linting
    runs-on: ubuntu-18.04

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.6
      uses: actions/setup-python@v2
      with:
        python-version: 3.6  # lint with minimal version supported (3.6 in 18.04)
    - name: Install dependencies
      run: |
        echo "${{ github.event_name }}! ${{ github.event.action }}"
        python -m pip install --upgrade pip
        python -m pip install flake8
    - name: Lint with flake8
      run: |
        flake8 .

  build_docker_image:
    name: Build docker image
    runs-on: ubuntu-20.04
    needs: [test]
    steps:
      - uses: actions/checkout@v2
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1
      - name: Build Docker image
        run: |
          docker build -t screamshotter_ci:latest .
      - name: Upload image
        uses: ishworkh/docker-image-artifact-upload@v1
        with:
          image: "screamshotter_ci:latest"
